/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasEscritorio;

import Controlador.ControladorAbrirMesa;
import Controlador.VistaAbrirMesa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Apuestas.TipoApuesta;
import modelo.Crupier;
import modelo.Fachada;
import modelo.Mesa;
import vistasEscritorio.PanelCrupier;

/**
 *
 * @author acarretto
 */
public class ConfiguracionDeMesa extends javax.swing.JFrame implements VistaAbrirMesa{

    private ControladorAbrirMesa cm;
    
    
    public ConfiguracionDeMesa(Crupier c) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CONFIGURACION DE MESA");
        cm = new ControladorAbrirMesa(this, c);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaTipoApuestas = new javax.swing.JList();
        btnAbrirMesa = new javax.swing.JButton();
        slcTipoApuesta = new javax.swing.JComboBox();
        btnQuitar = new javax.swing.JButton();
        btnAgregarTa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaTipoApuestas.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                listaTipoApuestasComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(listaTipoApuestas);

        btnAbrirMesa.setText("Abrir Mesa");
        btnAbrirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMesaActionPerformed(evt);
            }
        });

        slcTipoApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slcTipoApuestaActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnAgregarTa.setText("Agregar");
        btnAgregarTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnAbrirMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(slcTipoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnAgregarTa)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQuitar)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slcTipoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarTa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnAbrirMesa)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaTipoApuestasComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_listaTipoApuestasComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_listaTipoApuestasComponentAdded

    private void btnAbrirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMesaActionPerformed
        abrirMesa();
        
    }//GEN-LAST:event_btnAbrirMesaActionPerformed

    private void slcTipoApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slcTipoApuestaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_slcTipoApuestaActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        if(listaTipoApuestas.getSelectedValue() != null){
         quitarDeLista((TipoApuesta)listaTipoApuestas.getSelectedValue());
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione un tipo de apuesta");
        }    
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAgregarTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTaActionPerformed
         
         if(slcTipoApuesta.getSelectedItem() != null){
         agregarALista((TipoApuesta)slcTipoApuesta.getSelectedItem());
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de apuesta");
        }    
    }//GEN-LAST:event_btnAgregarTaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    private void agregarALista(TipoApuesta ta) {
       cm.agregarTipo(ta);
    }
    
    private void quitarDeLista(TipoApuesta ta){
        cm.quitarTipo(ta);
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirMesa;
    private javax.swing.JButton btnAgregarTa;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaTipoApuestas;
    private javax.swing.JComboBox slcTipoApuesta;
    // End of variables declaration//GEN-END:variables

    
    
    
   

    @Override
    public void actualizarMesasHabilitadas(ArrayList<Mesa> mesasHabilitadas) {
     
    }

     
    @Override
    public void mostrarTiposApuestaLista(ArrayList<TipoApuesta> dameTiposDeApuestaObligatorios) {
        listaTipoApuestas.setListData(dameTiposDeApuestaObligatorios.toArray()); 
    }

    
    
    @Override
    public void mostrarTiposApuestaCombo(ArrayList<TipoApuesta> tiposDeApuesta) {
         for(TipoApuesta ta:tiposDeApuesta){
           slcTipoApuesta.addItem(ta);
            }
        }
    

    public void abrirMesa() {
            cm.abrirMesa();
    }

    @Override
    public void error(String msjeError) {
         JOptionPane.showMessageDialog(this, msjeError);
    }

    @Override
    public void abrirPanel() {
        new PanelCrupier(this, false, cm.getC()).setVisible(true);
    }
    

}
