/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistasEscritorio;

import Controlador.ControladorPanelJugador;
import Controlador.VistaPanelJugador;
import Excepciones.ApuestaException;
import Observador.Observable;
import Observador.Observador;
import componente.PanelRuleta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Apuesta;
import modelo.Casillero;
import modelo.Fachada;
import modelo.Jugador;
import modelo.Mesa;
import modelo.Numero;
import modelo.Ronda;

/**
 *
 * @author acarretto
 */
public class PanelJugador extends javax.swing.JDialog implements VistaPanelJugador {

  
    
    /**
     * Creates new form PanelJugador
     */
   // private int valorSelec;
    private ControladorPanelJugador cpj;
        
    public PanelJugador(java.awt.Frame parent, boolean modal, Jugador j, Mesa m)  {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        cpj = new ControladorPanelJugador(this, j, m);
        apostar();
    }

    public PanelRuleta getRuleta() {
        return ruleta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruleta = new componente.PanelRuleta();
        asdasdasd = new javax.swing.JLabel();
        saldoJugador = new javax.swing.JLabel();
        labelMEsa = new javax.swing.JLabel();
        numeroRonda = new javax.swing.JLabel();
        labelNumMesa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNumRonda = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JLabel();
        labelNomCompleto = new javax.swing.JLabel();
        btnAbandonarMesa = new javax.swing.JButton();
        ficha1 = new javax.swing.JButton();
        ficha5 = new javax.swing.JButton();
        ficha10 = new javax.swing.JButton();
        ficha50 = new javax.swing.JButton();
        ficha100 = new javax.swing.JButton();
        labelUltimoNumero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStatsJugador = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblValorOcurrencia = new javax.swing.JTable();
        numMesa = new javax.swing.JLabel();
        numSorteado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(880, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        asdasdasd.setText("SALDO DISPONIBLE:  $");

        saldoJugador.setText("0");

        labelMEsa.setText("Ruleta #");

        numeroRonda.setText("Ronda #");

        labelNumRonda.setText("0");

        nombreJugador.setText("JUGADOR:");

        labelNomCompleto.setText("name");

        btnAbandonarMesa.setText("Abandonar Mesa");
        btnAbandonarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarMesaActionPerformed(evt);
            }
        });

        ficha1.setText("1");
        ficha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha1ActionPerformed(evt);
            }
        });

        ficha5.setText("5");
        ficha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha5ActionPerformed(evt);
            }
        });

        ficha10.setText("10");
        ficha10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha10ActionPerformed(evt);
            }
        });

        ficha50.setText("50");
        ficha50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha50ActionPerformed(evt);
            }
        });

        ficha100.setText("100");
        ficha100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha100ActionPerformed(evt);
            }
        });

        labelUltimoNumero.setText("Numero Sorteado:");

        tblStatsJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ronda", "Total apostado", "Ganado", "Perdido", "Balance"
            }
        ));
        jScrollPane2.setViewportView(tblStatsJugador);

        tblValorOcurrencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Valor", "Ocurrencia"
            }
        ));
        jScrollPane3.setViewportView(tblValorOcurrencia);

        numMesa.setText("numRuleta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(labelNumMesa)
                        .addGap(278, 278, 278)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ruleta, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(737, 737, 737)
                        .addComponent(btnAbandonarMesa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(ficha5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(ficha10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(ficha50, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(ficha100, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asdasdasd)
                                .addGap(18, 18, 18)
                                .addComponent(saldoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(labelMEsa)
                                .addGap(6, 6, 6)
                                .addComponent(numMesa)
                                .addGap(61, 61, 61)
                                .addComponent(numeroRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(labelNumRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreJugador)
                                .addGap(18, 18, 18)
                                .addComponent(labelNomCompleto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelUltimoNumero)
                                .addGap(32, 32, 32)
                                .addComponent(numSorteado)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asdasdasd)
                    .addComponent(saldoJugador)
                    .addComponent(labelMEsa)
                    .addComponent(numMesa)
                    .addComponent(numeroRonda)
                    .addComponent(labelNumRonda)
                    .addComponent(nombreJugador)
                    .addComponent(labelNomCompleto))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumMesa)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ficha1)
                        .addComponent(ficha5)
                        .addComponent(ficha10)
                        .addComponent(ficha100)
                        .addComponent(ficha50))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelUltimoNumero)
                        .addComponent(numSorteado)))
                .addGap(24, 24, 24)
                .addComponent(ruleta, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnAbandonarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ficha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha1ActionPerformed
        cpj.guardarFichaApostada(1);
      
    }//GEN-LAST:event_ficha1ActionPerformed

    private void ficha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha5ActionPerformed
        cpj.guardarFichaApostada(5);
        
    }//GEN-LAST:event_ficha5ActionPerformed

    private void ficha10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha10ActionPerformed
       cpj.guardarFichaApostada(10);
       
    }//GEN-LAST:event_ficha10ActionPerformed

    private void ficha50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha50ActionPerformed
       cpj.guardarFichaApostada(50);
      
    }//GEN-LAST:event_ficha50ActionPerformed

    private void ficha100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha100ActionPerformed
        cpj.guardarFichaApostada(100);
      
    }//GEN-LAST:event_ficha100ActionPerformed

    private void btnAbandonarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarMesaActionPerformed
        // TODO add your handling code here:
        cpj.abandonarMesa();
        
    }//GEN-LAST:event_btnAbandonarMesaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asdasdasd;
    private javax.swing.JButton btnAbandonarMesa;
    private javax.swing.JButton ficha1;
    private javax.swing.JButton ficha10;
    private javax.swing.JButton ficha100;
    private javax.swing.JButton ficha5;
    private javax.swing.JButton ficha50;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelMEsa;
    private javax.swing.JLabel labelNomCompleto;
    private javax.swing.JLabel labelNumMesa;
    private javax.swing.JLabel labelNumRonda;
    private javax.swing.JLabel labelUltimoNumero;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JLabel numMesa;
    private javax.swing.JLabel numSorteado;
    private javax.swing.JLabel numeroRonda;
    private componente.PanelRuleta ruleta;
    private javax.swing.JLabel saldoJugador;
    private javax.swing.JTable tblStatsJugador;
    private javax.swing.JTable tblValorOcurrencia;
    // End of variables declaration//GEN-END:variables

    
    public void apostar(){
       
        ruleta.agregar(new PanelRuleta.Escuchador() {
           
            @Override
            public void celdaSeleccionada(int ucc) {
                cpj.apostar(ucc);
            }
        });
    }
    
    
    @Override
    public void activarCasilleros(ArrayList<Casillero> casilleros) {
        for (Casillero c: casilleros) {
            ruleta.getApuesta(c.getUcc());
            ruleta.habilitar(c.getUcc(), true);
        }
    }
    
    @Override
    public void desactivarCasilleros() {
         for (int i = 0; i < 51; i++) {
            //La idea es poner la cantidad de casilleros que tiene la ruleta pero nose que metodo es.
            ruleta.habilitar(i, false);
        }
    }
    
//    
//    
//    @Override
//    public void mostrarSaldo(int v) {
//        saldoJugador.setText(v+"");
//    }
//
//    @Override
//    public void mostrarNumMesa(int v) {
//        numMesa.setText(v+"");
//    }
//
//    @Override
//    public void mostrarNumRonda(int v) {
//        labelNumMesa.setText(v+"");
//    }
//
//    @Override
//    public void mostrarUltimoNum(int v) {
//        numSorteado.setText(v+"");
//    }

    @Override
    public void mostrarNombre(String texto) {
        labelNomCompleto.setText(texto);
    }

    @Override
    public void actualizarApuesta(Apuesta a) {
                ruleta.setApuesta(a.getCasillero().getUcc(), a.getValor());
              saldoJugador.setText(a.getJugador().getSaldoActual()+"");
            }


    @Override
    public void error(String e) {
        JOptionPane.showMessageDialog(this, e);
    }

    @Override
    public void actualizoNumeroSorteado(int num) {
        numSorteado.setText(num+"");
    }

    @Override
    public void limpiarPanel() {
       
        ruleta.limpiar();
    }

    @Override
    public void pausarRuleta() {
        ruleta.pausar();
    }

    @Override
    public void actualizarSaldo(Jugador jugador) {
        saldoJugador.setText(jugador.getSaldoActual()+"");
    }

    @Override
    public void reanudarRuleta() {
        ruleta.reanudar();
    }

    @Override
    public void desactivarExit() {
       btnAbandonarMesa.disable();
    }


    @Override
    public void actualizarTablaStatsJugador(ArrayList<Ronda> rondasTotales, int totalApostadoJ, int ganado, int perdido, int balance) {
        DefaultTableModel stats = new DefaultTableModel();
        stats.addColumn("Ronda");
        stats.addColumn("Total Apostado");
        stats.addColumn("Ganancias");
        stats.addColumn("Perdidas");
        stats.addColumn("Balance");
        stats.setRowCount(5);
        int fila = 0;
       
            stats.setValueAt(rondasTotales.size(), fila, 0);
            stats.setValueAt(totalApostadoJ, fila, 1);
            stats.setValueAt(ganado, fila, 2);
            stats.setValueAt(perdido,  fila, 3);
            stats.setValueAt(balance, fila, 4);
           
    
        tblStatsJugador.setModel(stats);
        
    }

    @Override
    public void cerrarYPagarMesa() {
        
      cpj.abandonarMesa();
       
    }
    
    @Override
    public void cierroPanel(){
     dispose();
    }

    
    @Override
   public void actualizarTablaStatsJugador(ArrayList<Ronda> rondasTotales, Jugador j) {
       
       //No encontramos otra forma de por ronda traer distintos datos por ronda para 1 jugador
       
    DefaultTableModel stats = (DefaultTableModel) tblStatsJugador.getModel();
   
    for (int i = 0; i < rondasTotales.size(); i++) {
        stats.setRowCount(rondasTotales.size());

        Ronda r = rondasTotales.get(i);
        Object[] rowData = new Object[5]; 

        rowData[0] = i + 1; // Ronda
        rowData[1] = r.totalApostado(j);
        rowData[2] = r.totalGanadoPorJugador(j);
        rowData[3] = r.totalPerdidoPorJugador(j);
        rowData[4] = r.balanceJugador(j);


        stats.addRow(rowData);
    }
}



   public void actualizarTablaOcurrencia(Mesa m) {
    DefaultTableModel stats = new DefaultTableModel();
    stats.addColumn("Valor");
    stats.addColumn("Ocurrencia");


    stats.setRowCount(m.getRondas().size());

    int fila = 0;

    for (Ronda r : m.getRondas()) {
        stats.setValueAt(r.getNumSorteado(), fila, 0);
        stats.setValueAt(m.ocurrencia(r.getNumSorteado()), fila, 1);
        fila++;
    }

    tblValorOcurrencia.setModel(stats);
}
   
}
    
    
    

    
    
    
