/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistasEscritorio;

import Controlador.ControladorPanelCrupier;
import Controlador.VistaPanelCrupier;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Apuesta;
import modelo.Casillero;
import modelo.Crupier;
import modelo.Efectos.Efecto;
import modelo.Jugador;
import modelo.Ronda;

/**
 *
 * @author acarretto
 */
public class PanelCrupier extends javax.swing.JDialog implements VistaPanelCrupier {

    public ControladorPanelCrupier cpc;
   // private final Map<Integer, Cell> cells;
    
    /**
     * Creates new form PanelCrupier
     */
    public PanelCrupier(java.awt.Frame parent, boolean modal, Crupier c) {
        super(parent, modal);
        initComponents();
        
        this.cpc = new ControladorPanelCrupier(this, c);
        setLocationRelativeTo(parent);
        
         ruleta.limpiar();
        
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruleta = new componente.PanelRuleta();
        ascasc = new javax.swing.JLabel();
        numMesa = new javax.swing.JLabel();
        ultimoNumeroS = new javax.swing.JLabel();
        btnLanzarPagar = new javax.swing.JButton();
        rdthrsdth = new javax.swing.JLabel();
        assd = new javax.swing.JLabel();
        asfs = new javax.swing.JLabel();
        asd = new javax.swing.JLabel();
        btnCerrarMesa = new javax.swing.JButton();
        comboEfectos = new javax.swing.JComboBox();
        numRonda = new javax.swing.JLabel();
        totalApuestas = new javax.swing.JLabel();
        balancePanelCrupier = new javax.swing.JLabel();
        listaUltimosLanzamientos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstadistica = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JugadoresYSaldo = new javax.swing.JTable();
        cantApuestas = new javax.swing.JLabel();
        ultimos3Nums = new javax.swing.JLabel();
        montoTotalRonda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ascasc.setText("Monto:");

        numMesa.setText("0");

        btnLanzarPagar.setText("Lanzar / Pagar");
        btnLanzarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarPagarActionPerformed(evt);
            }
        });

        rdthrsdth.setText("Ultimo numero:");

        assd.setText("Balance: $ - ");

        asfs.setText("Ronda #");

        asd.setText("Ruleta #");

        btnCerrarMesa.setText("Cerrar Mesa");
        btnCerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMesaActionPerformed(evt);
            }
        });

        comboEfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEfectosActionPerformed(evt);
            }
        });

        numRonda.setText("0");

        totalApuestas.setText("Apuestas:");

        balancePanelCrupier.setText("0");

        listaUltimosLanzamientos.setText("Ultimos Lanzamientos:");

        tablaEstadistica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ronda", "Balance Anterior", "Apuestas", "Recoleccion", "Liquidacion", "Balance Posterior"
            }
        ));
        jScrollPane1.setViewportView(tablaEstadistica);

        JugadoresYSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jugador", "Saldo"
            }
        ));
        jScrollPane2.setViewportView(JugadoresYSaldo);

        cantApuestas.setText("0");

        montoTotalRonda.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ruleta, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalApuestas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantApuestas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ascasc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(assd)
                        .addGap(34, 34, 34)
                        .addComponent(balancePanelCrupier)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(montoTotalRonda)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asfs)
                        .addGap(34, 34, 34)
                        .addComponent(numRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(asd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numMesa)
                        .addGap(49, 49, 49)
                        .addComponent(btnCerrarMesa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnLanzarPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(rdthrsdth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ultimoNumeroS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaUltimosLanzamientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ultimos3Nums))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asfs)
                    .addComponent(asd)
                    .addComponent(btnCerrarMesa)
                    .addComponent(numRonda)
                    .addComponent(balancePanelCrupier)
                    .addComponent(numMesa)
                    .addComponent(assd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalApuestas)
                        .addComponent(ascasc)
                        .addComponent(btnLanzarPagar)
                        .addComponent(cantApuestas)
                        .addComponent(montoTotalRonda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdthrsdth)
                        .addComponent(ultimoNumeroS)))
                .addGap(18, 18, 18)
                .addComponent(ruleta, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaUltimosLanzamientos)
                    .addComponent(ultimos3Nums))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarPagarActionPerformed
           cpc.lanzarBola((Efecto)comboEfectos.getSelectedItem());
           ruleta.limpiar();
    }//GEN-LAST:event_btnLanzarPagarActionPerformed

    private void btnCerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMesaActionPerformed
        cpc.cerrarMesa();
        this.dispose();
    }//GEN-LAST:event_btnCerrarMesaActionPerformed

    private void comboEfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEfectosActionPerformed

    }//GEN-LAST:event_comboEfectosActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JugadoresYSaldo;
    private javax.swing.JLabel ascasc;
    private javax.swing.JLabel asd;
    private javax.swing.JLabel asfs;
    private javax.swing.JLabel assd;
    private javax.swing.JLabel balancePanelCrupier;
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnLanzarPagar;
    private javax.swing.JLabel cantApuestas;
    private javax.swing.JComboBox comboEfectos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listaUltimosLanzamientos;
    private javax.swing.JLabel montoTotalRonda;
    private javax.swing.JLabel numMesa;
    private javax.swing.JLabel numRonda;
    private javax.swing.JLabel rdthrsdth;
    private componente.PanelRuleta ruleta;
    private javax.swing.JTable tablaEstadistica;
    private javax.swing.JLabel totalApuestas;
    private javax.swing.JLabel ultimoNumeroS;
    private javax.swing.JLabel ultimos3Nums;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ocultarMonedas() {
//        for(Cell c:cells){
//            
//        }
    }

    @Override
    public void activarCasilleros(ArrayList<Casillero> CasillerosDisponibles) {
        for (Casillero c: CasillerosDisponibles ) {
            
            ruleta.habilitar(c.getUcc(), true);
            
        }
    }

    @Override
    public void cargarEfectos(ArrayList<Efecto> listaEfectos) {
            for(Efecto e:listaEfectos){
                comboEfectos.addItem(e);
            }
    }

    @Override
    public void actualizoNumeroSorteado(int numSorteado) {
        ultimoNumeroS.setText(numSorteado+"");
    }
 
    @Override
    public void actualizarDatos(ArrayList<Apuesta> apuestas) {
        for(Apuesta a: apuestas){
            ruleta.setApuesta(a.getCasillero().getUcc(), ruleta.getApuesta(a.getCasillero().getUcc())+ a.getValor());
            cantApuestas.setText(cantApuestas.getText()+"");
        }
    }


    @Override
    public void pausarRuleta() {
        ruleta.pausar();
        ruleta.limpiar();
    }

    @Override
    public void startRuleta() {
        ruleta.reanudar();
    }

    @Override
    public void limpiarPanel() {
      ruleta.limpiar();
    }

    

    
    public void desactivarCasilleros() {
         for (int i = 0; i < 51; i++) {
            //La idea es poner la cantidad de casilleros que tiene la ruleta pero nose que metodo es.
            ruleta.habilitar(i, false);
    }

    }

    @Override
    public void actualizarValoresInicialesMesa(double balance, int numMesa, int numR) {
        this.balancePanelCrupier.setText(balance+"");
        this.numMesa.setText(numMesa+"");
        this.numRonda.setText(numR+"");
        this.montoTotalRonda.setText(0 + "");
        this.cantApuestas.setText(0 + "");
    }


    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    @Override
    public void actualizarTablaJugadoresActivos(ArrayList<Jugador> jugadoresActivos) {
        
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Nombre");
        datos.addColumn("Saldo");
        datos.setRowCount(jugadoresActivos.size());
        int fila = 0;
        
        for(Jugador j:jugadoresActivos){
            datos.setValueAt(j.getNomCompleto(), fila, 0);
            datos.setValueAt(j.getSaldoActual(), fila, 1);
            fila++;
        }
        JugadoresYSaldo.setModel(datos);     
        
        
    }

    @Override
    public void actualizarTablaEstadistica(ArrayList<Ronda> rondas) {
     
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Ronda");
        datos.addColumn("Balance previo");
        datos.addColumn("Apuestas");
        datos.addColumn("Ganancias");
        datos.addColumn("Perdidas");
        datos.addColumn("Balance posterior");
        datos.setRowCount(rondas.size());
        int fila = 0;
       
        for(Ronda r:rondas){
            datos.setValueAt(fila+1, fila, 0);
            datos.setValueAt(r.getBalancePrevio(), fila, 1);
            datos.setValueAt(r.getApuestasJugadores().size(), fila, 2);
            datos.setValueAt(r.getApuestasPerdedoras(), fila, 3);
            datos.setValueAt(r.getApuestasGanadoras(), fila, 4);
            datos.setValueAt(r.getBalancePosterior(), fila, 5);
            fila++;
        }
        tablaEstadistica.setModel(datos);     
        
        
        
    }

    @Override
    public void mostrarUltimosNumeros(String ultimos3) {

            ultimos3Nums.setText(ultimos3);
       
    }

    @Override
    public void setCantApuestas(int size) {
       cantApuestas.setText(size + "");
    }

    @Override
    public void actualizoMontoRonda(int totalApostado) {
        montoTotalRonda.setText(totalApostado + "");
    }
    
    
    
    
    
    
}
         

