/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasEscritorio;

import Controlador.ControladorEntrarAMesa;
import Controlador.VistaEntrarAMesa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Fachada;
import modelo.Jugador;
import modelo.Mesa;

/**
 *
 * @author acarretto
 */
public class SeleccionDeMesa extends javax.swing.JFrame implements VistaEntrarAMesa{

    /**
     * Creates new form SeleccionDeMesa
     */
    private ControladorEntrarAMesa cem;
    
    public SeleccionDeMesa(Jugador j) {
        initComponents();
        setTitle("MESAS ABIERTAS");
        setLocationRelativeTo(null);
        this.cem = new ControladorEntrarAMesa(this, j);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMesasAbiertas = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        nomJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione una mesa:");

        listMesasAbiertas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMesasAbiertasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMesasAbiertas);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido a la Ruleta Online");

        nomJugador.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomJugador)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        if(listMesasAbiertas.getSelectedValue()!= null){
            entrarAMesa();
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para ingresar");
        }    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void listMesasAbiertasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMesasAbiertasValueChanged
        // TODO add your handling code here:
        //cem.getF().avisar(Fachada.eventos.dameMesasHabilitadas); COMO ES???????
        
    }//GEN-LAST:event_listMesasAbiertasValueChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMesasAbiertas;
    private javax.swing.JLabel nomJugador;
    // End of variables declaration//GEN-END:variables

    
    public void entrarAMesa() {
       cem.entrarALaMesa((Mesa)listMesasAbiertas.getSelectedValue());
    }

    @Override
    public void error(String msjeError) {
        JOptionPane.showMessageDialog(this, msjeError);
    }

    @Override
    public void cargarMesasIniciales(ArrayList<Mesa> mesas) {
         listMesasAbiertas.setListData(mesas.toArray());
    }

    @Override
    public void actualizarNombre(Jugador j) {
       nomJugador.setText(j.getNomCompleto());
    }

    @Override
    public void proximoCasoDeUso(Jugador j, Mesa m) {
        new PanelJugador(this, false, j, m).setVisible(true);
    }
    
    
    
    
}
